server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: user-service-swagger
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/**
        - id: cms-master-swagger
          uri: http://localhost:8090
          predicates:
            - Path=/cms-master/**
        - id: authorization-service
          uri: http://localhost:8081
          predicates:
            - Path=/authorization-service/**
          filters:
            - RewritePath=/authorization-service/(?<path>.*), /$\{path}
