server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\\{path}/v3/api-docs
        - id: cms-master-service
          uri: http://cms-master:8080
          predicates:
            - Path=/cms-master/**
        - id: authorization-service
          uri: http://auth-service:8080
          predicates:
            - Path=/oauth/**
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user-service/**
