# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Build with Maven
      run: docker build -t ghcr.io/$GITHUB_REPOSITORY/master:${{github.run_number}} .
    - name: Push to registry
      run: docker push ghcr.io/$GITHUB_REPOSITORY/master:${{github.run_number}}
      
  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'
    steps:
    - name: Run docker swarm
      run: docker service update --image ghcr.io/$GITHUB_REPOSITORY/master:${{github.run_number}} gateway
